<?php require 'header.phtml' ?>

<h1><?php echo $this->get('pageTitle'); ?></h1>

<a href="<?php echo $this->app->getConfig('siteURL') ?>/Index/hello">I have a surprise for you...</a>

<div class="left">
    <p>
        Welcome to ezRPG! Login now!
    </p>
</div>
<div class="right">
    <form method="post" action="Login" name="login">
        <label for="username">Username</label>
        <input type="text" name="username" />

        <label for="password">Password</label>
        <input type="password" name="password" />
		
        <input name="login" type="submit" class="button" value="Login">
    </form>
</div>  

<?php require 'footer.phtml' ?>
