<!DOCTYPE html>
<html lang="en">
<?php $siteConfig = $this->container['config']['site']; ?>
	<head>
		<meta name="description" content="ezRPG Project, the free, open source browser-based game engine!" />
		<meta name="keywords" content="" />
		
		<link type="text/css" rel="stylesheet" href="<?php echo $this->getThemeUrl('css/style.css'); ?>">
		<title>ezRPG Installation</title>
	</head>
	<body>
	<body>

		<div id="wrapper">
 
			<div id="header">
				<span id="title"><a href="./">ezRPG <span>2.0</span></a></span>
			</div>
			<div id="body_wrap">
				<div id="body">
					<div id="sidebar">
						<ul>
							<li>
								Requirements
							</li>
							<li>
								License
							</li>
							<li>
								Configuration
							</li>
							<li>
								Admin
							</li>
						</ul>
					</div>
					<div id="gamebody">
