<?php

include("header.phtml");
$license = $this->get('license');

?>
<p>ezRPG is distributed under the <strong><a href="http://www.openfoundry.org/en/licenses/31" title="More information">BSD 3-clause</a></strong> license.<br /><br />
The license can be found below, or in within the LICENSE.md file in the root directory of this application.
We encourage you to read through this license now.</p>
<div style="font-family: monospace;white-space: pre;line-height:.8em;font-size:.95em">
<?php echo $license; ?>
</div>
<p>
Continuing with this installation means you acknowledge and accept this condition of using ezRPG.<br />
<a href="<?php echo $this->getUrl('installer/config'); ?>"><i>I understand, continue.</i></a>
</p>
<?php include("footer.phtml"); ?>