<?php include 'header.phtml';

$data = $this->get('data');
?>
<table cellspacing="0" border="0" width="100%">
	<tr>
		<th colspan="2" align="left">Requirement</th>
	</tr>
	<tr>
		<td width="25%">
			PHP Version
		</td>
		<td>
			<font color="<?php echo ($data['php_version']) ? "green" : "red"; ?>"><?php echo PHP_VERSION; ?></font>
		</td>
	</tr>
	<tr>
		<td width="25%">
			Config File Writable
		</td>
		<td>
			<font color="<?php echo ($data['writable']['config']) ? "green\">Writable" : "red\">Not Writable"; ?></font>
				  </td>
				  </tr>
				  <tr>
				  <td width="25%">
			Settings File Writable
		</td>
		<td>
			<font color="<?php echo ($data['writable']['settings']) ? "green\">Writable" : "red\">Not Writable"; ?></font>
				  </td>
				  </tr>
				  </table>

				  <?php if ($data['passed']) { ?>

					  <a href="<?php echo $this->getUrl('installer/license'); ?>">Continue</a>

			
				  <?php } else { 
					  
					  echo '<ul>';
					  foreach ($this->get('errors') as $error) {
						  echo '<li>' . $error . '</li>';
					  }
					  echo '</ul>';
					  
				  }