<?php 

include 'header.phtml';
$checks = $this->get('checks');

?>
<style>
	.good { color: green; }
	.bad { color: red; }
	.warn { color: orange; }
	.box { padding: 3px 2px; border: solid 1px #DDD; border-radius: 2px; display: block; }
</style>
<table style="width: 100%">
	<tr>
		<th colspan="2" align="left">Requirement</th>
	</tr>
	<?php foreach($checks as $title => $results) { ?>
		<tr>
			<td width="25%">
				<?php echo $title; ?>
			</td>
			<td>
				<span class="<?php echo ($results['passed'] ? 'good' : ($results['required'] ? 'bad' : 'warn')); ?>">
					<?php echo ($results['passed'] ? 'Passed' : 'Failed'); ?>
				</span>
			</td>
		</tr>
	<?php } ?>
</table>
<?php 

$warnings = array();
$errors = array();

foreach($checks as $check) {
	if ($check['passed'] == false) {
		if ($check['required'] == false) {
			$warnings[] = $check['message'];
		} else {
			$errors[] = $check['message'];
		}
	}
}

if (count($errors) == 0) {
	echo '<br /><br /><div style="text-align:center"><button style="margin:0" onclick="javascript:location = \'' . $this->getUrl('installer/license') . '\'">Continue</button></div>';
} 

if (count($errors) > 0 || count($warnings) > 0) {
	echo '<br /><strong>Not all prerequisites have been met, please see advice below on how to solve this issue.</strong>';
	
	if (count($errors) > 0) {
		echo '<p><strong>Errors</strong><br />These are the problems the installer found that needs attention:<br />';
		foreach($errors as $error) {
			echo '<span class="bad box">' . $error . '</span>';
		}
		
		echo '<strong><i>Please rectify these issues before continuing.</i></strong></p>';
	}
	
	if (count($warnings) > 0) {
		echo '<p><strong>Warngings</strong><br />These are the problems the installer found that doesn\'t need your immediate attention, but are worth looking into to get all the power of ezRPG:<br />';
		foreach($warnings as $warning) {
				echo '<span class="warn box">' . $warning . '</span>';
		}
		echo '</p>';
	}
	
	echo '<div style="text-align:center"><button style="margin:0" onclick="javascript:location.reload()">Refresh</button></div><br /><br />';
}

include 'footer.phtml';