<?php require 'header.phtml' ?>

<strong>Acl</strong>
<pre class="prettyprint lang-php">
<?php var_dump($this->get('acl_stack')); ?>
</pre>

<hr />
<strong>Set Password</strong>
<form method="post" action="/DevTools/setpassword">

	<label>Username</label>
	<input type="text" name="username">
	<br />
	
	<label>Password</label>
	<input type="password" name="password">
	<br />
	
	<input type="submit">
</form>
<?php require 'footer.phtml' ?>