				</div>
			</div>
		</div>
		
		<div id="footer"></div>
		
		<div id="copyright">
			<a href="<?php echo $this->getUrl('Legal'); ?>">Terms of Service</a> | <a href="<?php echo $this->getUrl('Privacy'); ?>">Privacy Policy</a><br />
			Copyright &copy; <?php echo date('Y'); ?> <a <a href="<?php echo $this->getUrl('Index'); ?>" target="_parent"><strong><?php echo $siteConfig['name']; ?></strong></a>.<br />
			<small>Powered by <a href="//ezrpgproject.org" target="_blank">ezRPG</a>.</small>
		</div>
	
	</body>
	
</html>