<?php 

$loggedIn = $this->container['app']->getModel('session')->isLoggedIn();

?>
<ul>
	<?php if ($loggedIn) { ?>
	<li><a href="<?php echo $this->getUrl('Home'); ?>">Home</a></li>
	<li><a href="<?php echo $this->getUrl('Logout'); ?>">Logout</a></li>
	
	<?php if ($this->container['acl']->hasRole('administrator')) { ?>
	<li><a href="<?php echo $this->getUrl('admin/index'); ?>">Admin Panel</a></li>
	<?php } ?>
	<?php } else { ?>
	<li><a href="<?php echo $this->getUrl('Index');  ?>">Home</a></li>
	<li><a href="<?php echo $this->getUrl('Register');  ?>">Register</a></li>
	<?php } ?>
</ul>