<?php require 'header.phtml' ?>

<h1><?php echo $this->get('pageTitle') ?></h1>

<p>
Want to join the fun? Fill out the form below to register!
</p>
<?php 

$post_data = array(
	'username' => isset($_POST['username']) ? $_POST['username'] : '',
	'email' => isset($_POST['email']) ? $_POST['email'] : '',
	'password' => isset($_POST['password']) ? $_POST['password'] : '',
);

?>
<form method="post" action="register">
    <table width="80%" align=center>
        <tr>
            <td valign=top>
                <label>Username</label>
                <input type="text" size="40" name="username" value="<?php echo $post_data['username']; ?>" />
                <label>Email</label>
                <input type="text" size="40" name="email" value="<?php echo $post_data['email']; ?>" />
            </td>
            <td valign=top>
                <label>Password</label>
                <input type="password" size="40" name="password"  value="<?php echo $post_data['password']; ?>" />

                <label>Verify Password</label>
                <input type="password" size="40" name="password2" />
            </td>
        </tr>
        <tr>
            <td colspan=2 align="center">
				<input type="hidden" name="verify" value="0" />
                <br />
                <input name="register" type="submit" value="Register" class="button" zindex="5" />
            </td>
        </tr>
                
    </table>
</form>

<script src="<?php echo $this->getUrl('views/js/modules/register/security.js'); ?>"></script>
<script>
	$.run('ready', 'security.botCheck');
</script>
 
<?php require 'footer.phtml' ?>
