<!DOCTYPE html>
<html lang="en">
<?php $siteConfig = $this->container['config']->get('site'); ?>
  <head>
	<meta charset="utf-8">
	<title><?php echo $siteConfig['name']; ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Le styles -->
	<link href="<?php echo $this->getThemeUrl('css/bootstrap.css'); ?>" rel="stylesheet">
	<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&lang=php&autoload=true"></script>
	<link href="<?php echo $this->getThemeUrl('css/prettify.css'); ?>" rel="stylesheet">
	
  </head>

  <body>

	<div class="container">

	   <h3 class="muted"><?php echo $siteConfig['name']; ?></h3>
	  <div class="masthead">
		<div class="navbar">
		  <div class="navbar-inner">
			<div class="container">
			  <ul class="nav">
				<?php if ($this->get('loggedIn')) { ?>
				<li><a href="<?php echo $this->getUrl('Home'); ?>">Home</a></li>
				<li><a href="<?php echo $this->getUrl('Logout'); ?>">Logout</a></li>
				<?php } else { ?>
				<li><a href="<?php echo $this->getUrl('Index');  ?>">Home</a></li>
				<li><a href="<?php echo $this->getUrl('Register');  ?>">Register</a></li>
				<?php } ?>
			  </ul>
			</div>
		  </div>
		</div><!-- /.navbar -->
	  </div>
	  
	  
	<?php echo $this->get('msg'); ?>
