<?php require 'header.phtml' ?>

<h1><?php echo $this->get('pageTitle') ?></h1>

<div class="left">
<p>
<strong>Username</strong>: <?php echo $this->get('player')->username ?><br />
<strong>Email</strong>: <?php echo $this->get('player')->email ?><br />
<strong>Registered</strong>: <?php echo $this->get('player')->registered ?><br />
<strong>Kills/Deaths</strong>: <?php echo $this->get('player')->kills ?> / <?php $this->get('player')->deaths ?><br />
<br />

<?php if ( $this->get('player')->stat_points > 0 ) { ?>
You have stat points left over!<br />
<a href="index.php?mod=StatPoints"><strong>Spend them now!</strong></a>
<?php } else { ?>
You have no extra stat points to spend.
<?php } ?>
</p>
</div>
 

<div class="right">
<p>
<strong>Level</strong>: <?php echo $this->get('player')->level ?><br />
<strong>Gold</strong>: <?php echo $this->get('player')->money ?><br />
<br />
<strong>Strength</strong>: <?php echo $this->get('player')->strength ?><br />
<strong>Vitality</strong>: <?php echo $this->get('player')->vitality ?><br />
<strong>Agility</strong>: <?php echo $this->get('player')->agility ?><br />
<strong>Dexterity</strong>: <?php echo $this->get('player')->dexterity ?><br />
</p>
</div>
<?php require 'footer.phtml' ?>