<?php require 'header.phtml' ?>

<h1><?php echo $this->get('pageTitle'); ?></h1>


<div class="row">
	<div class="span6">
		<p>
			Welcome to ezRPG! Login now!<br />
			<a href="<?php echo $this->getUrl('Index/hello'); ?>">I have a surprise for you...</a>
		</p>
	</div>
	
	<div class="span6">
		<form method="post" action="<?php echo $this->getUrl('Login'); ?>" name="login">
			<div class="control-group">
				<label for="username">Username</label>
				<input type="text" name="username" />
			</div>
	
			<div class="control-group">
		  		<label for="password">Password</label>
				<input type="password" name="password" />
			</div>
	
			<div class="control-group">
				<input name="login" type="submit" class="btn btn-primary" value="Login">
			</div>
		</form>
	</div>
</div>

<?php require 'footer.phtml' ?>