CREATE TABLE if not exists `<pre>setting` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `value` text,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `setting` (`id`, `parent_id`, `title`, `value`, `active`) VALUES
(1, NULL, 'site', NULL, 1),
(2, 1, 'name', '', 1),
(3, 1, 'url', '', 1),
(4, 1, 'theme', 'default', 1),
(5, NULL, 'router', NULL, 1),
(6, 5, 'partialRoutes', 'true', 1),
(7, 5, 'routes', 'array()', 1),
(8, NULL, 'cache', NULL, 1),
(9, 8, 'use', 'false', 1),
(10, 8, 'prefix', 'ezRPG', 1),
(11, 8, 'ttl', '60', 1),
(12, NULL, 'security', NULL, 1),
(13, 12, 'hashRounds', '11', 1),
(14, 12, 'hashSaltSize', '16', 1),
(15, 12, 'passwordStrength', '1', 1),
(16, 12, 'login', NULL, 1),
(17, 16, 'showInvalidLoginReason', 'true', 1),
(18, 16, 'returnUsernameOnFailure', 'true', 1),
(19, 12, 'showExceptions', 'true', 1),
(20, 12, 'acl', NULL, 1),
(21, 20, 'use', 'true', 1),
(22, 20, 'rootRole', 'root', 1),
(23, NULL, 'accounts', NULL, 1),
(24, 23, 'requireActivation', 'false', 1),
(25, 23, 'emailActivation', 'false', 1);