<?php require dirname(dirname(__DIR__)) . '/header.phtml' ?>

<h1>Player Listing</h1>

<table style="width:100%">
<tr>
	<th>ID</th>
	<th>Username</th>
	<th>Email</th>
	<th>Active</th>
</tr>
<?php 
foreach($this->get('players') as $player) {
	?>
	<tr>
		<th><?php echo $player['id']; ?></th>
		<th><?php echo $player['username']; ?></th>
		<th><?php echo $player['email']; ?></th>
		<th><?php echo ($player['active'] == 0 ? '<span class="msg fail" style="margin:0">No</span>' : '<span class="msg good" style="margin:0">Yes</span>'); ?></th>
	</tr>
	<?php 
} 
?>
</table>

<?php require dirname(dirname(__DIR__)) . '/footer.phtml' ?>